# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  user_name: "coopers"



---

# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dphello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo hello $(cat /etc/config/user_name); sleep 1; done"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: user-config