# coopers @ 2024-07
# kubectl apply -f maria.yml  # create 重要: 第一步创建
# kubectl delete -f maria.yml  # delete
# kubectl get cm # list
# kubectl get secret # list
# kubectl get pod -o wide  # 重要: 第二步获取 maria-pod 的 IP 地址 10.42.0.44

apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm

data:
  DATABASE: 'db'
  USER: 'wp'
  PASSWORD: '123'
  ROOT_PASSWORD: '123'
---
apiVersion: v1
kind: Pod
metadata:
  name: maria-pod
  labels:
    app: wordpress
    role: database

spec:
  containers:
  - image: mariadb:10
    name: maria
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306

    envFrom:
    - prefix: 'MARIADB_'
      configMapRef:
        name: maria-cm



## 测试验证:
```
kubectl exec -it maria-pod -- /bin/bash
mysql -u wp -p123 db

```